spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create  # (1) 스키마 자동 생성
    show-sql: true      # (2) SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print
  sql:
    init:
      data-locations: classpath*:db/h2/data.sql
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 882323060278-spjfmu1mvtvdb9g0fnujqf95lrugi5so.apps.googleusercontent.com           # (1)
            clientSecret: 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  # (2)
            scope:
              - email
              - profile



logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
server:
  servlet:
    encoding:
      force-response: true
mail:
  address:
    admin: admin@gmail.com
jwt:
  key:
    secret: vyvyvy123123123123123123151616515161552651651565145615
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420